# Generated by Django 3.2.16 on 2023-01-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
    ]
