# Generated by Django 3.2.16 on 2023-01-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_correct_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks_Of_User',
        ),
    ]
