# Generated by Django 3.2.16 on 2023-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_delete_marks_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_amount',
            field=models.IntegerField(default=0),
        ),
    ]
