# Generated by Django 3.2.16 on 2023-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_score_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
